//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDGUtil.ConversionTool {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnResultTest", Namespace="http://microsoft.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class ReturnResultTest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Track1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Track2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Track1 {
            get {
                return this.Track1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Track1Field, value) != true)) {
                    this.Track1Field = value;
                    this.RaisePropertyChanged("Track1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Track2 {
            get {
                return this.Track2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Track2Field, value) != true)) {
                    this.Track2Field = value;
                    this.RaisePropertyChanged("Track2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="ConversionTool.ConversionToolSoap")]
    public interface ConversionToolSoap {
        
        // CODEGEN: Generating message contract since element name InPinData from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/EvertecKeyConversion", ReplyAction="*")]
        SDGUtil.ConversionTool.EvertecKeyConversionResponse EvertecKeyConversion(SDGUtil.ConversionTool.EvertecKeyConversionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/EvertecKeyConversion", ReplyAction="*")]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.EvertecKeyConversionResponse> EvertecKeyConversionAsync(SDGUtil.ConversionTool.EvertecKeyConversionRequest request);
        
        // CODEGEN: Generating message contract since element name InPinData from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConvertPinData", ReplyAction="*")]
        SDGUtil.ConversionTool.ConvertPinDataResponse ConvertPinData(SDGUtil.ConversionTool.ConvertPinDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConvertPinData", ReplyAction="*")]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.ConvertPinDataResponse> ConvertPinDataAsync(SDGUtil.ConversionTool.ConvertPinDataRequest request);
        
        // CODEGEN: Generating message contract since element name InPinDataClearText from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConvertPinDataToPin", ReplyAction="*")]
        SDGUtil.ConversionTool.ConvertPinDataToPinResponse ConvertPinDataToPin(SDGUtil.ConversionTool.ConvertPinDataToPinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConvertPinDataToPin", ReplyAction="*")]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.ConvertPinDataToPinResponse> ConvertPinDataToPinAsync(SDGUtil.ConversionTool.ConvertPinDataToPinRequest request);
        
        // CODEGEN: Generating message contract since element name InPinData from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConvertPinDataClearText", ReplyAction="*")]
        SDGUtil.ConversionTool.ConvertPinDataClearTextResponse ConvertPinDataClearText(SDGUtil.ConversionTool.ConvertPinDataClearTextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConvertPinDataClearText", ReplyAction="*")]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.ConvertPinDataClearTextResponse> ConvertPinDataClearTextAsync(SDGUtil.ConversionTool.ConvertPinDataClearTextRequest request);
        
        // CODEGEN: Generating message contract since element name InputStr from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DecryptRover", ReplyAction="*")]
        SDGUtil.ConversionTool.DecryptRoverResponse DecryptRover(SDGUtil.ConversionTool.DecryptRoverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DecryptRover", ReplyAction="*")]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.DecryptRoverResponse> DecryptRoverAsync(SDGUtil.ConversionTool.DecryptRoverRequest request);
        
        // CODEGEN: Generating message contract since element name InputStr from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/Test", ReplyAction="*")]
        SDGUtil.ConversionTool.TestResponse Test(SDGUtil.ConversionTool.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/Test", ReplyAction="*")]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.TestResponse> TestAsync(SDGUtil.ConversionTool.TestRequest request);
        
        // CODEGEN: Generating message contract since element name InputStr from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DecryptTrack2Rover", ReplyAction="*")]
        SDGUtil.ConversionTool.DecryptTrack2RoverResponse DecryptTrack2Rover(SDGUtil.ConversionTool.DecryptTrack2RoverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DecryptTrack2Rover", ReplyAction="*")]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.DecryptTrack2RoverResponse> DecryptTrack2RoverAsync(SDGUtil.ConversionTool.DecryptTrack2RoverRequest request);
        
        // CODEGEN: Generating message contract since element name InputStr from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DecryptTrack1Rover", ReplyAction="*")]
        SDGUtil.ConversionTool.DecryptTrack1RoverResponse DecryptTrack1Rover(SDGUtil.ConversionTool.DecryptTrack1RoverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/DecryptTrack1Rover", ReplyAction="*")]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.DecryptTrack1RoverResponse> DecryptTrack1RoverAsync(SDGUtil.ConversionTool.DecryptTrack1RoverRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EvertecKeyConversionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EvertecKeyConversion", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.EvertecKeyConversionRequestBody Body;
        
        public EvertecKeyConversionRequest() {
        }
        
        public EvertecKeyConversionRequest(SDGUtil.ConversionTool.EvertecKeyConversionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class EvertecKeyConversionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InPinData;
        
        public EvertecKeyConversionRequestBody() {
        }
        
        public EvertecKeyConversionRequestBody(string InPinData) {
            this.InPinData = InPinData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EvertecKeyConversionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EvertecKeyConversionResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.EvertecKeyConversionResponseBody Body;
        
        public EvertecKeyConversionResponse() {
        }
        
        public EvertecKeyConversionResponse(SDGUtil.ConversionTool.EvertecKeyConversionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class EvertecKeyConversionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EvertecKeyConversionResult;
        
        public EvertecKeyConversionResponseBody() {
        }
        
        public EvertecKeyConversionResponseBody(string EvertecKeyConversionResult) {
            this.EvertecKeyConversionResult = EvertecKeyConversionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertPinDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertPinData", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.ConvertPinDataRequestBody Body;
        
        public ConvertPinDataRequest() {
        }
        
        public ConvertPinDataRequest(SDGUtil.ConversionTool.ConvertPinDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ConvertPinDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InPinData;
        
        public ConvertPinDataRequestBody() {
        }
        
        public ConvertPinDataRequestBody(string InPinData) {
            this.InPinData = InPinData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertPinDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertPinDataResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.ConvertPinDataResponseBody Body;
        
        public ConvertPinDataResponse() {
        }
        
        public ConvertPinDataResponse(SDGUtil.ConversionTool.ConvertPinDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ConvertPinDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertPinDataResult;
        
        public ConvertPinDataResponseBody() {
        }
        
        public ConvertPinDataResponseBody(string ConvertPinDataResult) {
            this.ConvertPinDataResult = ConvertPinDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertPinDataToPinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertPinDataToPin", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.ConvertPinDataToPinRequestBody Body;
        
        public ConvertPinDataToPinRequest() {
        }
        
        public ConvertPinDataToPinRequest(SDGUtil.ConversionTool.ConvertPinDataToPinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ConvertPinDataToPinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InPinDataClearText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PAN;
        
        public ConvertPinDataToPinRequestBody() {
        }
        
        public ConvertPinDataToPinRequestBody(string InPinDataClearText, string PAN) {
            this.InPinDataClearText = InPinDataClearText;
            this.PAN = PAN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertPinDataToPinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertPinDataToPinResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.ConvertPinDataToPinResponseBody Body;
        
        public ConvertPinDataToPinResponse() {
        }
        
        public ConvertPinDataToPinResponse(SDGUtil.ConversionTool.ConvertPinDataToPinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ConvertPinDataToPinResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertPinDataToPinResult;
        
        public ConvertPinDataToPinResponseBody() {
        }
        
        public ConvertPinDataToPinResponseBody(string ConvertPinDataToPinResult) {
            this.ConvertPinDataToPinResult = ConvertPinDataToPinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertPinDataClearTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertPinDataClearText", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.ConvertPinDataClearTextRequestBody Body;
        
        public ConvertPinDataClearTextRequest() {
        }
        
        public ConvertPinDataClearTextRequest(SDGUtil.ConversionTool.ConvertPinDataClearTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ConvertPinDataClearTextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InPinData;
        
        public ConvertPinDataClearTextRequestBody() {
        }
        
        public ConvertPinDataClearTextRequestBody(string InPinData) {
            this.InPinData = InPinData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertPinDataClearTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertPinDataClearTextResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.ConvertPinDataClearTextResponseBody Body;
        
        public ConvertPinDataClearTextResponse() {
        }
        
        public ConvertPinDataClearTextResponse(SDGUtil.ConversionTool.ConvertPinDataClearTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ConvertPinDataClearTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertPinDataClearTextResult;
        
        public ConvertPinDataClearTextResponseBody() {
        }
        
        public ConvertPinDataClearTextResponseBody(string ConvertPinDataClearTextResult) {
            this.ConvertPinDataClearTextResult = ConvertPinDataClearTextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptRoverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptRover", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.DecryptRoverRequestBody Body;
        
        public DecryptRoverRequest() {
        }
        
        public DecryptRoverRequest(SDGUtil.ConversionTool.DecryptRoverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class DecryptRoverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InputStr;
        
        public DecryptRoverRequestBody() {
        }
        
        public DecryptRoverRequestBody(string InputStr) {
            this.InputStr = InputStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptRoverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptRoverResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.DecryptRoverResponseBody Body;
        
        public DecryptRoverResponse() {
        }
        
        public DecryptRoverResponse(SDGUtil.ConversionTool.DecryptRoverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class DecryptRoverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DecryptRoverResult;
        
        public DecryptRoverResponseBody() {
        }
        
        public DecryptRoverResponseBody(string DecryptRoverResult) {
            this.DecryptRoverResult = DecryptRoverResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(SDGUtil.ConversionTool.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class TestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InputStr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string KSN;
        
        public TestRequestBody() {
        }
        
        public TestRequestBody(string InputStr, string KSN) {
            this.InputStr = InputStr;
            this.KSN = KSN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(SDGUtil.ConversionTool.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SDGUtil.ConversionTool.ReturnResultTest TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(SDGUtil.ConversionTool.ReturnResultTest TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptTrack2RoverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptTrack2Rover", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.DecryptTrack2RoverRequestBody Body;
        
        public DecryptTrack2RoverRequest() {
        }
        
        public DecryptTrack2RoverRequest(SDGUtil.ConversionTool.DecryptTrack2RoverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class DecryptTrack2RoverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InputStr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string KSN;
        
        public DecryptTrack2RoverRequestBody() {
        }
        
        public DecryptTrack2RoverRequestBody(string InputStr, string KSN) {
            this.InputStr = InputStr;
            this.KSN = KSN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptTrack2RoverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptTrack2RoverResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.DecryptTrack2RoverResponseBody Body;
        
        public DecryptTrack2RoverResponse() {
        }
        
        public DecryptTrack2RoverResponse(SDGUtil.ConversionTool.DecryptTrack2RoverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class DecryptTrack2RoverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DecryptTrack2RoverResult;
        
        public DecryptTrack2RoverResponseBody() {
        }
        
        public DecryptTrack2RoverResponseBody(string DecryptTrack2RoverResult) {
            this.DecryptTrack2RoverResult = DecryptTrack2RoverResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptTrack1RoverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptTrack1Rover", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.DecryptTrack1RoverRequestBody Body;
        
        public DecryptTrack1RoverRequest() {
        }
        
        public DecryptTrack1RoverRequest(SDGUtil.ConversionTool.DecryptTrack1RoverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class DecryptTrack1RoverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InputStr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string KSN;
        
        public DecryptTrack1RoverRequestBody() {
        }
        
        public DecryptTrack1RoverRequestBody(string InputStr, string KSN) {
            this.InputStr = InputStr;
            this.KSN = KSN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptTrack1RoverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptTrack1RoverResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public SDGUtil.ConversionTool.DecryptTrack1RoverResponseBody Body;
        
        public DecryptTrack1RoverResponse() {
        }
        
        public DecryptTrack1RoverResponse(SDGUtil.ConversionTool.DecryptTrack1RoverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class DecryptTrack1RoverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DecryptTrack1RoverResult;
        
        public DecryptTrack1RoverResponseBody() {
        }
        
        public DecryptTrack1RoverResponseBody(string DecryptTrack1RoverResult) {
            this.DecryptTrack1RoverResult = DecryptTrack1RoverResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConversionToolSoapChannel : SDGUtil.ConversionTool.ConversionToolSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConversionToolSoapClient : System.ServiceModel.ClientBase<SDGUtil.ConversionTool.ConversionToolSoap>, SDGUtil.ConversionTool.ConversionToolSoap {
        
        public ConversionToolSoapClient() {
        }
        
        public ConversionToolSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConversionToolSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionToolSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionToolSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SDGUtil.ConversionTool.EvertecKeyConversionResponse SDGUtil.ConversionTool.ConversionToolSoap.EvertecKeyConversion(SDGUtil.ConversionTool.EvertecKeyConversionRequest request) {
            return base.Channel.EvertecKeyConversion(request);
        }
        
        public string EvertecKeyConversion(string InPinData) {
            SDGUtil.ConversionTool.EvertecKeyConversionRequest inValue = new SDGUtil.ConversionTool.EvertecKeyConversionRequest();
            inValue.Body = new SDGUtil.ConversionTool.EvertecKeyConversionRequestBody();
            inValue.Body.InPinData = InPinData;
            SDGUtil.ConversionTool.EvertecKeyConversionResponse retVal = ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).EvertecKeyConversion(inValue);
            return retVal.Body.EvertecKeyConversionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.EvertecKeyConversionResponse> SDGUtil.ConversionTool.ConversionToolSoap.EvertecKeyConversionAsync(SDGUtil.ConversionTool.EvertecKeyConversionRequest request) {
            return base.Channel.EvertecKeyConversionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SDGUtil.ConversionTool.EvertecKeyConversionResponse> EvertecKeyConversionAsync(string InPinData) {
            SDGUtil.ConversionTool.EvertecKeyConversionRequest inValue = new SDGUtil.ConversionTool.EvertecKeyConversionRequest();
            inValue.Body = new SDGUtil.ConversionTool.EvertecKeyConversionRequestBody();
            inValue.Body.InPinData = InPinData;
            return ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).EvertecKeyConversionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SDGUtil.ConversionTool.ConvertPinDataResponse SDGUtil.ConversionTool.ConversionToolSoap.ConvertPinData(SDGUtil.ConversionTool.ConvertPinDataRequest request) {
            return base.Channel.ConvertPinData(request);
        }
        
        public string ConvertPinData(string InPinData) {
            SDGUtil.ConversionTool.ConvertPinDataRequest inValue = new SDGUtil.ConversionTool.ConvertPinDataRequest();
            inValue.Body = new SDGUtil.ConversionTool.ConvertPinDataRequestBody();
            inValue.Body.InPinData = InPinData;
            SDGUtil.ConversionTool.ConvertPinDataResponse retVal = ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).ConvertPinData(inValue);
            return retVal.Body.ConvertPinDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.ConvertPinDataResponse> SDGUtil.ConversionTool.ConversionToolSoap.ConvertPinDataAsync(SDGUtil.ConversionTool.ConvertPinDataRequest request) {
            return base.Channel.ConvertPinDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<SDGUtil.ConversionTool.ConvertPinDataResponse> ConvertPinDataAsync(string InPinData) {
            SDGUtil.ConversionTool.ConvertPinDataRequest inValue = new SDGUtil.ConversionTool.ConvertPinDataRequest();
            inValue.Body = new SDGUtil.ConversionTool.ConvertPinDataRequestBody();
            inValue.Body.InPinData = InPinData;
            return ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).ConvertPinDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SDGUtil.ConversionTool.ConvertPinDataToPinResponse SDGUtil.ConversionTool.ConversionToolSoap.ConvertPinDataToPin(SDGUtil.ConversionTool.ConvertPinDataToPinRequest request) {
            return base.Channel.ConvertPinDataToPin(request);
        }
        
        public string ConvertPinDataToPin(string InPinDataClearText, string PAN) {
            SDGUtil.ConversionTool.ConvertPinDataToPinRequest inValue = new SDGUtil.ConversionTool.ConvertPinDataToPinRequest();
            inValue.Body = new SDGUtil.ConversionTool.ConvertPinDataToPinRequestBody();
            inValue.Body.InPinDataClearText = InPinDataClearText;
            inValue.Body.PAN = PAN;
            SDGUtil.ConversionTool.ConvertPinDataToPinResponse retVal = ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).ConvertPinDataToPin(inValue);
            return retVal.Body.ConvertPinDataToPinResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.ConvertPinDataToPinResponse> SDGUtil.ConversionTool.ConversionToolSoap.ConvertPinDataToPinAsync(SDGUtil.ConversionTool.ConvertPinDataToPinRequest request) {
            return base.Channel.ConvertPinDataToPinAsync(request);
        }
        
        public System.Threading.Tasks.Task<SDGUtil.ConversionTool.ConvertPinDataToPinResponse> ConvertPinDataToPinAsync(string InPinDataClearText, string PAN) {
            SDGUtil.ConversionTool.ConvertPinDataToPinRequest inValue = new SDGUtil.ConversionTool.ConvertPinDataToPinRequest();
            inValue.Body = new SDGUtil.ConversionTool.ConvertPinDataToPinRequestBody();
            inValue.Body.InPinDataClearText = InPinDataClearText;
            inValue.Body.PAN = PAN;
            return ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).ConvertPinDataToPinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SDGUtil.ConversionTool.ConvertPinDataClearTextResponse SDGUtil.ConversionTool.ConversionToolSoap.ConvertPinDataClearText(SDGUtil.ConversionTool.ConvertPinDataClearTextRequest request) {
            return base.Channel.ConvertPinDataClearText(request);
        }
        
        public string ConvertPinDataClearText(string InPinData) {
            SDGUtil.ConversionTool.ConvertPinDataClearTextRequest inValue = new SDGUtil.ConversionTool.ConvertPinDataClearTextRequest();
            inValue.Body = new SDGUtil.ConversionTool.ConvertPinDataClearTextRequestBody();
            inValue.Body.InPinData = InPinData;
            SDGUtil.ConversionTool.ConvertPinDataClearTextResponse retVal = ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).ConvertPinDataClearText(inValue);
            return retVal.Body.ConvertPinDataClearTextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.ConvertPinDataClearTextResponse> SDGUtil.ConversionTool.ConversionToolSoap.ConvertPinDataClearTextAsync(SDGUtil.ConversionTool.ConvertPinDataClearTextRequest request) {
            return base.Channel.ConvertPinDataClearTextAsync(request);
        }
        
        public System.Threading.Tasks.Task<SDGUtil.ConversionTool.ConvertPinDataClearTextResponse> ConvertPinDataClearTextAsync(string InPinData) {
            SDGUtil.ConversionTool.ConvertPinDataClearTextRequest inValue = new SDGUtil.ConversionTool.ConvertPinDataClearTextRequest();
            inValue.Body = new SDGUtil.ConversionTool.ConvertPinDataClearTextRequestBody();
            inValue.Body.InPinData = InPinData;
            return ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).ConvertPinDataClearTextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SDGUtil.ConversionTool.DecryptRoverResponse SDGUtil.ConversionTool.ConversionToolSoap.DecryptRover(SDGUtil.ConversionTool.DecryptRoverRequest request) {
            return base.Channel.DecryptRover(request);
        }
        
        public string DecryptRover(string InputStr) {
            SDGUtil.ConversionTool.DecryptRoverRequest inValue = new SDGUtil.ConversionTool.DecryptRoverRequest();
            inValue.Body = new SDGUtil.ConversionTool.DecryptRoverRequestBody();
            inValue.Body.InputStr = InputStr;
            SDGUtil.ConversionTool.DecryptRoverResponse retVal = ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).DecryptRover(inValue);
            return retVal.Body.DecryptRoverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.DecryptRoverResponse> SDGUtil.ConversionTool.ConversionToolSoap.DecryptRoverAsync(SDGUtil.ConversionTool.DecryptRoverRequest request) {
            return base.Channel.DecryptRoverAsync(request);
        }
        
        public System.Threading.Tasks.Task<SDGUtil.ConversionTool.DecryptRoverResponse> DecryptRoverAsync(string InputStr) {
            SDGUtil.ConversionTool.DecryptRoverRequest inValue = new SDGUtil.ConversionTool.DecryptRoverRequest();
            inValue.Body = new SDGUtil.ConversionTool.DecryptRoverRequestBody();
            inValue.Body.InputStr = InputStr;
            return ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).DecryptRoverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SDGUtil.ConversionTool.TestResponse SDGUtil.ConversionTool.ConversionToolSoap.Test(SDGUtil.ConversionTool.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public SDGUtil.ConversionTool.ReturnResultTest Test(string InputStr, string KSN) {
            SDGUtil.ConversionTool.TestRequest inValue = new SDGUtil.ConversionTool.TestRequest();
            inValue.Body = new SDGUtil.ConversionTool.TestRequestBody();
            inValue.Body.InputStr = InputStr;
            inValue.Body.KSN = KSN;
            SDGUtil.ConversionTool.TestResponse retVal = ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.TestResponse> SDGUtil.ConversionTool.ConversionToolSoap.TestAsync(SDGUtil.ConversionTool.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<SDGUtil.ConversionTool.TestResponse> TestAsync(string InputStr, string KSN) {
            SDGUtil.ConversionTool.TestRequest inValue = new SDGUtil.ConversionTool.TestRequest();
            inValue.Body = new SDGUtil.ConversionTool.TestRequestBody();
            inValue.Body.InputStr = InputStr;
            inValue.Body.KSN = KSN;
            return ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SDGUtil.ConversionTool.DecryptTrack2RoverResponse SDGUtil.ConversionTool.ConversionToolSoap.DecryptTrack2Rover(SDGUtil.ConversionTool.DecryptTrack2RoverRequest request) {
            return base.Channel.DecryptTrack2Rover(request);
        }
        
        public string DecryptTrack2Rover(string InputStr, string KSN) {
            SDGUtil.ConversionTool.DecryptTrack2RoverRequest inValue = new SDGUtil.ConversionTool.DecryptTrack2RoverRequest();
            inValue.Body = new SDGUtil.ConversionTool.DecryptTrack2RoverRequestBody();
            inValue.Body.InputStr = InputStr;
            inValue.Body.KSN = KSN;
            SDGUtil.ConversionTool.DecryptTrack2RoverResponse retVal = ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).DecryptTrack2Rover(inValue);
            return retVal.Body.DecryptTrack2RoverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.DecryptTrack2RoverResponse> SDGUtil.ConversionTool.ConversionToolSoap.DecryptTrack2RoverAsync(SDGUtil.ConversionTool.DecryptTrack2RoverRequest request) {
            return base.Channel.DecryptTrack2RoverAsync(request);
        }
        
        public System.Threading.Tasks.Task<SDGUtil.ConversionTool.DecryptTrack2RoverResponse> DecryptTrack2RoverAsync(string InputStr, string KSN) {
            SDGUtil.ConversionTool.DecryptTrack2RoverRequest inValue = new SDGUtil.ConversionTool.DecryptTrack2RoverRequest();
            inValue.Body = new SDGUtil.ConversionTool.DecryptTrack2RoverRequestBody();
            inValue.Body.InputStr = InputStr;
            inValue.Body.KSN = KSN;
            return ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).DecryptTrack2RoverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SDGUtil.ConversionTool.DecryptTrack1RoverResponse SDGUtil.ConversionTool.ConversionToolSoap.DecryptTrack1Rover(SDGUtil.ConversionTool.DecryptTrack1RoverRequest request) {
            return base.Channel.DecryptTrack1Rover(request);
        }
        
        public string DecryptTrack1Rover(string InputStr, string KSN) {
            SDGUtil.ConversionTool.DecryptTrack1RoverRequest inValue = new SDGUtil.ConversionTool.DecryptTrack1RoverRequest();
            inValue.Body = new SDGUtil.ConversionTool.DecryptTrack1RoverRequestBody();
            inValue.Body.InputStr = InputStr;
            inValue.Body.KSN = KSN;
            SDGUtil.ConversionTool.DecryptTrack1RoverResponse retVal = ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).DecryptTrack1Rover(inValue);
            return retVal.Body.DecryptTrack1RoverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SDGUtil.ConversionTool.DecryptTrack1RoverResponse> SDGUtil.ConversionTool.ConversionToolSoap.DecryptTrack1RoverAsync(SDGUtil.ConversionTool.DecryptTrack1RoverRequest request) {
            return base.Channel.DecryptTrack1RoverAsync(request);
        }
        
        public System.Threading.Tasks.Task<SDGUtil.ConversionTool.DecryptTrack1RoverResponse> DecryptTrack1RoverAsync(string InputStr, string KSN) {
            SDGUtil.ConversionTool.DecryptTrack1RoverRequest inValue = new SDGUtil.ConversionTool.DecryptTrack1RoverRequest();
            inValue.Body = new SDGUtil.ConversionTool.DecryptTrack1RoverRequestBody();
            inValue.Body.InputStr = InputStr;
            inValue.Body.KSN = KSN;
            return ((SDGUtil.ConversionTool.ConversionToolSoap)(this)).DecryptTrack1RoverAsync(inValue);
        }
    }
}
